version: '3.9'


services:
  client:
    build:
      context: .
    command: python client.py
    environment:
      - LOG_CONF=logging.json
      - SERVER_PORT=8000
    volumes:
      - .:/code
  server:
    build:
      context: .
    command: python server.py
    expose:
      - "8000"
    environment:
      - LOG_CONF=logging.json
      - SERVER_PORT=8000
    volumes:
      - .:/code

